//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::{pubkey, Pubkey};

/// `wavebreak` program ID.
pub const WAVEBREAK_ID: Pubkey = pubkey!("waveQX2yP3H1pVU8djGvEHmYg8uamQ84AuyGtpsrXTF");
